# Generated by Django 3.0.4 on 2020-03-11 10:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Post date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homepage',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
