# Generated by Django 3.0.4 on 2020-03-12 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200311_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='category',
            field=models.CharField(choices=[('dt', 'Downloadable Templates'), ('il', 'Illustrations'), ('cp', 'Client Projects')], default='DOWNLOADABLE', max_length=2),
        ),
    ]
