# Generated by Django 3.0.4 on 2020-03-12 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('wagtailcore', '0045_assign_unlock_grouppagepermission'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('home', '0005_auto_20200312_0358'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WorksPage',
        ),
    ]
