# Generated by Django 3.0.4 on 2020-03-12 06:31

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.contrib.taggit
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0001_squashed_0021'),
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('works', '0002_blogpagegalleryimage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlogPageGalleryImage',
            new_name='WorkPageGalleryImage',
        ),
        migrations.CreateModel(
            name='WorksPageTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_items', to='works.WorkPage')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='works_workspagetag_items', to='taggit.Tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='workpage',
            name='tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='works.WorksPageTag', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
